# Generated by Django 5.2 on 2025-04-21 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('criteria_type', models.CharField(choices=[('mandatory', 'Mandatory'), ('optional', 'Optional')], max_length=10)),
                ('applicable_path', models.CharField(choices=[('talent', 'Exceptional Talent'), ('promise', 'Exceptional Promise'), ('both', 'Both Paths')], max_length=10)),
                ('number_of_documents', models.IntegerField(default=2)),
                ('notion_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('personal_statement', 'Personal Statement'), ('cv', 'CV'), ('recommendation', 'Recommendation Letter'), ('evidence', 'Evidence Document'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('review', 'Under Review')], default='not_started', max_length=15)),
                ('content', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('word_count', models.IntegerField(default=0)),
                ('page_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('related_criteria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='document_manager.eligibilitycriteria')),
            ],
        ),
    ]
