# Generated by Django 5.2 on 2025-04-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0002_documentcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='document',
            name='generation_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('personal_statement', 'Personal Statement'), ('cv', 'CV'), ('recommendation', 'Recommendation Letter'), ('evidence', 'Evidence Document'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='user_documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('draft', 'Draft'), ('in_progress', 'In Progress'), ('reviewing', 'Under Review'), ('completed', 'Completed'), ('archived', 'Archived')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
