# Generated by Django 5.2 on 2025-04-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0004_document_generated_file_document_original_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_chosen',
            field=models.BooleanField(default=False, help_text="Indicates if this document is the user's chosen version for submission"),
        ),
    ]
