# Generated by Django 5.2 on 2025-04-21 21:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('account_type', models.CharField(choices=[('free', 'Free'), ('pay_once', 'Pay Once'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='free', max_length=20)),
                ('application_stage', models.CharField(choices=[('assessment', 'Initial Assessment'), ('preparation', 'Document Preparation'), ('review', 'Application Review'), ('submission', 'Submission Stage'), ('post_submission', 'Post Submission')], default='assessment', max_length=20)),
                ('visa_path', models.CharField(choices=[('talent', 'Exceptional Talent'), ('promise', 'Exceptional Promise'), ('undecided', 'Undecided')], default='undecided', max_length=20)),
                ('is_technical', models.BooleanField(default=False)),
                ('is_business', models.BooleanField(default=False)),
                ('years_experience', models.IntegerField(default=0)),
                ('subscription_active', models.BooleanField(default=False)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('notify_guide_changes', models.BooleanField(default=True)),
                ('notify_app_updates', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_country', models.CharField(blank=True, max_length=100)),
                ('target_uk_region', models.CharField(blank=True, max_length=100)),
                ('tech_specializations', models.JSONField(blank=True, default=list)),
                ('assessment_completed', models.BooleanField(default=False)),
                ('documents_completed', models.JSONField(blank=True, default=dict)),
                ('ai_queries_used', models.IntegerField(default=0)),
                ('ai_queries_limit', models.IntegerField(default=5)),
                ('consultation_credits', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
