# Generated by Django 5.2 on 2025-04-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_application_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='document_status',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='documents_completed',
            field=models.BooleanField(default=False),
        ),
    ]
