# Generated by Django 5.2 on 2025-04-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_document_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_contribution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_innovation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_recognition',
            field=models.BooleanField(default=False),
        ),
    ]
