# Generated by Django 5.2 on 2025-04-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_github_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='successful_referrals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_referrals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('document', 'Document'), ('ai', 'AI Assistant'), ('assessment', 'Assessment'), ('expert', 'Expert Session'), ('notification', 'Notification'), ('referral_reward', 'Referral Reward')], max_length=20),
        ),
    ]
