# Generated by Django 5.2 on 2025-05-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquery',
            name='query_type',
            field=models.CharField(blank=True, default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='aiquery',
            name='tokens_used',
            field=models.IntegerField(default=0),
        ),
    ]
