# Generated by Django 5.2 on 2025-04-22 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_marketplace', '0002_alter_booking_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-scheduled_time']},
        ),
        migrations.AlterModelOptions(
            name='expert',
            options={'ordering': ['-success_rate', '-years_experience']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['price']},
        ),
        migrations.AddField(
            model_name='expert',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('limited', 'Limited Availability'), ('unavailable', 'Currently Unavailable')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='expert',
            name='certifications',
            field=models.TextField(blank=True, help_text='List your professional certifications'),
        ),
        migrations.AddField(
            model_name='expert',
            name='qualifications',
            field=models.TextField(blank=True, help_text='List your relevant academic qualifications'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='expert',
            name='bio',
            field=models.TextField(help_text='Describe your experience with Tech Nation visa applications'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='expert',
            name='success_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='expert',
            name='years_experience',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
