# Generated by Django 5.2 on 2025-04-23 19:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_marketplace', '0003_alter_booking_options_alter_expert_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expert',
            options={'ordering': ['-success_rate', '-years_experience'], 'verbose_name': 'Expert', 'verbose_name_plural': 'Experts'},
        ),
        migrations.AddField(
            model_name='expert',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='expert',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expert',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_expert', to=settings.AUTH_USER_MODEL),
        ),
    ]
