# Generated by Django 5.2 on 2025-05-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_marketplace', '0004_alter_expert_options_expert_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='linkedin_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
