# Generated by Django 5.2 on 2025-05-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_marketplace', '0006_remove_review_comment_remove_review_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='booking',
            name='deposit_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='deposit_payment_intent_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='dispute_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='dispute_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='dispute_winner',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('expert', 'Expert')], max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='final_payment_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='final_payment_intent_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='in_dispute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='meeting_completed_by_expert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='meeting_completed_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='meeting_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
