# Generated by Django 5.2 on 2025-05-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_marketplace', '0007_booking_deposit_amount_booking_deposit_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='google_meet_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
