# Generated by Django 5.2 on 2025-05-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_marketplace', '0008_booking_calendar_event_id_booking_google_meet_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='expert_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='expert_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payout_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='payout_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('completed_by_expert', 'Completed by Expert'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('dispute_resolved', 'Dispute Resolved'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
