# Generated by Django 5.2 on 2025-05-08 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_marketplace', '0009_booking_expert_completed_booking_expert_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='deposit_payment_intent_id',
            new_name='payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='calendar_event_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='deposit_paid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='final_payment_completed',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='final_payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='google_meet_link',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='meeting_completed_by_expert',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='meeting_completed_by_user',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payout_processed',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payout_processed_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='remaining_amount',
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_booking', to='expert_marketplace.service'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Payment Received'), ('confirmed', 'Expert Confirmed'), ('completed_by_expert', 'Completed by Expert'), ('completed', 'Completed'), ('disputed', 'In Dispute'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
