# Generated by Django 5.2 on 2025-05-08 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_marketplace', '0010_rename_deposit_payment_intent_id_booking_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert_review', to='expert_marketplace.booking'),
        ),
    ]
