# Generated by Django 5.2 on 2025-05-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_marketplace', '0011_alter_review_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='user',
        ),
        migrations.RemoveField(
            model_name='service',
            name='expert',
        ),
        migrations.RemoveField(
            model_name='review',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='dispute_description',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='dispute_resolved',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='dispute_winner',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='expert_completed',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='expert_completed_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='in_dispute',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='meeting_link',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_completed',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user_completed',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user_completed_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='scheduled_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='scheduled_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
