# Generated by Django 5.2 on 2025-05-08 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert_marketplace', '0012_remove_expert_user_remove_service_expert_and_more'),
        ('payments', '0003_remove_subscription_plan_remove_subscription_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expert',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
