# Generated by Django 5.2 on 2025-04-30 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_alter_referralsignup_referred_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referralsignup',
            options={},
        ),
        migrations.RenameField(
            model_name='referralcode',
            old_name='shares',
            new_name='successful_referrals',
        ),
        migrations.AddField(
            model_name='referralcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='referralsignup',
            name='points_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referralsignup',
            name='points_awarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referralsignup',
            name='referred_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_signups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='referralsignup',
            unique_together={('referral_code', 'referred_user')},
        ),
    ]
