# Generated by Django 5.2 on 2025-04-21 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotionPageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField()),
                ('content_hash', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='NotionChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=200)),
                ('change_type', models.CharField(choices=[('major', 'Major Change'), ('minor', 'Minor Change')], max_length=10)),
                ('description', models.TextField()),
                ('diff_html', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('current_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_changes', to='notion_monitor.notionpagesnapshot')),
                ('previous_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_changes', to='notion_monitor.notionpagesnapshot')),
            ],
        ),
    ]
