# Generated by Django 5.2 on 2025-05-08 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_marketplace', '0010_rename_deposit_payment_intent_id_booking_payment_intent_id_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_marketplace_bookings', to='expert_marketplace.service'),
        ),
    ]
